"""empty message

Revision ID: 527ee08e9050
Revises: ee244a58d835
Create Date: 2021-01-13 17:52:06.215432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527ee08e9050'
down_revision = 'ee244a58d835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_session_token')
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index('ix_user_session_token', ['session_token'], unique=False)

    # ### end Alembic commands ###
